name: Generate GitHub Activity Stats

on:
  push:
    branches:
      - main  # Adjust to your default branch name

jobs:
  generate-activity-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate GitHub Stats
        run: |
          npx githubocto/flat@v17 --token ${{ secrets.shoto }} --format=markdown --readme=./README.md --section=activity
