name: Generate GitHub Activity Stats

on:
  push:
    branches:
      - main  # Adjust to your default branch name

jobs:
  generate-activity-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Update to Node.js version 16
    

      - name: Install dependencies
        run: npm install github-readme-stats

      - name: Generate GitHub Stats
        run: npx github-readme-stats --fetch-stats=brianondiso
